name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          path: action

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "action/go.mod"
      - run: go version

      - name: Set up the action
        run: |
          make all      # build goveralls binaries
        working-directory: action

      - name: archive
        run: tar czvf action.tar.gz action
      - uses: actions/upload-artifact@v7
        with:
          name: action
          path: ./action.tar.gz

  # run tests with Go that supports go.mod
  test:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os: ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-24.04"]') || fromJSON('["ubuntu-24.04","ubuntu-22.04","ubuntu-24.04-arm","ubuntu-22.04-arm","macos-26","macos-14","macos-15-intel","windows-11-arm","windows-2025","windows-2022"]') }}
        go: ${{ github.actor == 'dependabot[bot]' && fromJSON('["1.26"]') || fromJSON('["1.21","1.22","1.23","1.24","1.25","1.26","oldstable","stable"]') }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - run: go version

      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: action
      - name: extract
        run: tar xzvf action.tar.gz
      - name: send coverage
        uses: ./action/
        with:
          parallel: true
          flag-name: ${{ runner.os }}-Go-${{ matrix.go }}
          shallow: true

  finish:
    needs:
      - build
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: action
      - name: extract
        run: tar xzvf action.tar.gz
      - name: finalize parallel build
        uses: ./action/
        with:
          parallel-finished: true
          shallow: true
